import { Movie } from "@/type";

export const MOVIES: Movie[] = [
  {
    id: 1,
    category: "Thriller",
    title: "3 days of a blind girl",
    synopsis: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad earum provident quas? Necessitatibus explicabo at quidem debitis autem perferendis repellat eligendi velit, dolores dicta reprehenderit beatae temporibus aliquam nam tempora.",
    year: "1993",
    country: "Hong-kong",
    director: "Chan Wing Chiu",
    casting: "Veronica Yip, Anthony wong",
    cover: "",
    hero: "",
    file: "",
    nbViews: 21,
    nbComments: 8,
    slug: "3-days-of-a-blind-girl",
  },
  {
    id: 2,
    category: "Action",
    title: "A toute épreuve",
    synopsis: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad earum provident quas? Necessitatibus explicabo at quidem debitis autem perferendis repellat eligendi velit, dolores dicta reprehenderit beatae temporibus aliquam nam tempora.",
    year: "1992",
    country: "Hong-kong",
    director: "John Woo",
    casting: "Chow Yun Fat, Anthony wong",
    cover: "",
    hero: "",
    file: "",
    nbViews: 10,
    nbComments: 8,
    slug: "a-toute-epreuve",
  },
  {
    id: 3,
    category: "Horreur",
    title: "L'enfer des zombies",
    synopsis: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad earum provident quas? Necessitatibus explicabo at quidem debitis autem perferendis repellat eligendi velit, dolores dicta reprehenderit beatae temporibus aliquam nam tempora.",
    year: "1980",
    country: "Italie",
    director: "Lucio Fulci",
    casting: "Tisa Farrow",
    cover: "",
    hero: "",
    file: "",
    nbViews: 21,
    nbComments: 8,
    slug: "l-enfer-des-zombies",
  },
  {
    id: 4,
    category: "Science-fiction",
    title: "Invasion Los-angeles",
    synopsis: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad earum provident quas? Necessitatibus explicabo at quidem debitis autem perferendis repellat eligendi velit, dolores dicta reprehenderit beatae temporibus aliquam nam tempora.",
    year: "1988",
    country: "Etats-Unis",
    director: "John Carpenter",
    casting: "Rody Piper",
    cover: "",
    hero: "",
    file: "",
    nbViews: 21,
    nbComments: 8,
    slug: "invasion-los-angeles",
  },
  {
    id: 5,
    category: "Rape and revenge",
    title: "Un justicier dans la ville",
    synopsis: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad earum provident quas? Necessitatibus explicabo at quidem debitis autem perferendis repellat eligendi velit, dolores dicta reprehenderit beatae temporibus aliquam nam tempora.",
    year: "1974",
    country: "Etats-Unis",
    director: "Michael Winner",
    casting: "Charles Bronson",
    cover: "",
    hero: "",
    file: "",
    nbViews: 21,
    nbComments: 8,
    slug: "un-justicier-dans-la-ville",
  },
  
  
];
